use chrono::NaiveDate;
use serde::Serialize;
use std::collections::HashMap;

use crate::scanner::node::Node;

use super::funds_type::{FundsSubType, FundsType};
use super::transaction::Transaction;
use super::util::{parse_currency, parse_date, parse_int, parse_string, parse_time};

#[derive(Debug, Serialize)]
pub struct Account {
    amounts: Vec<Amount>,
    currency_code: String,
    customer_account_number: String,
    number_of_records: Option<u32>,
    transactions: Vec<Transaction>,
    total: Option<u64>,
    value_date: Option<NaiveDate>,
    value_time: Option<String>,
}

impl Account {
    pub fn from_node(node: &Node, default_currency: &str) -> Result<Account, &'static str> {
        let header_fields = node.fields();
        if header_fields.len() < 7 {
            return Err("Invalid account header. Expected 7 fields, but found less.");
        }

        let trailer_fields = node.sibling_fields();
        if trailer_fields.len() < 3 {
            return Err("Invalid account trailer. Expected 3 fields, but found less.");
        }

        let txns_result = node
            .children
            .iter()
            .map(Transaction::from_node)
            .collect::<Result<Vec<Transaction>, &'static str>>();

        match txns_result {
            Err(e) => Err(e),
            Ok(transactions) => Ok(Account {
                amounts: Amount::parse(header_fields[3..].to_vec()),
                currency_code: parse_currency(header_fields[2], default_currency),
                customer_account_number: parse_string(header_fields[1]),
                number_of_records: parse_int(trailer_fields[2]),
                transactions,
                total: parse_int(trailer_fields[1]),
                value_date: None,
                value_time: None,
            }),
        }
    }
}

#[derive(Debug, Serialize)]
pub struct Amount {
    amount_type: AmountType,
    amount_type_code: String,
    amount: Option<i64>,
    availability: HashMap<u16, i64>,
    funds_type: FundsType,
    item_count: Option<u16>,
    value_date: Option<NaiveDate>,
    value_time: Option<String>,
}

impl Amount {
    fn parse(fields: Vec<&str>) -> Vec<Amount> {
        let mut amounts = Vec::new();
        let mut next_start_index = 0;

        while fields.len() > next_start_index + 1 {
            let amount_type_code = parse_string(fields[next_start_index]);
            let mut amount = Amount {
                amount: parse_int(fields[next_start_index + 1]),
                amount_type: AmountType::parse(&amount_type_code),
                amount_type_code,
                availability: HashMap::new(),
                funds_type: FundsType::parse(fields[next_start_index + 3]),
                item_count: parse_int(fields[next_start_index + 2]),
                value_date: None,
                value_time: None,
            };

            match amount.funds_type {
                FundsType::ValueDated => {
                    amount.value_date = parse_date(fields[next_start_index + 4]);
                    amount.value_time = parse_time(fields[next_start_index + 5]);
                    next_start_index = next_start_index + 6;
                }
                FundsType::DistributedAvailability(FundsSubType::S) => {
                    amount
                        .availability
                        .insert(0, parse_int(fields[next_start_index + 4]).unwrap());
                    amount
                        .availability
                        .insert(1, parse_int(fields[next_start_index + 5]).unwrap());
                    amount
                        .availability
                        .insert(2, parse_int(fields[next_start_index + 6]).unwrap());
                    next_start_index = next_start_index + 7;
                }
                FundsType::DistributedAvailability(FundsSubType::D) => {
                    let num_distributions = parse_int(fields[next_start_index + 4]).unwrap_or(0);
                    next_start_index = next_start_index + 5;

                    for _ in 0..num_distributions {
                        match (
                            parse_int(fields[next_start_index]),
                            parse_int(fields[next_start_index + 1]),
                        ) {
                            (Some(days), Some(amt)) => {
                                amount.availability.insert(days, amt);
                            }
                            _ => {}
                        }

                        next_start_index = next_start_index + 2;
                    }
                }
                _ => {
                    next_start_index = next_start_index + 4;
                }
            }

            amounts.push(amount);
        }

        return amounts;
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AmountType {
    AchNetPosition,
    AchSettlementCredits,
    AchSettlementDebits,
    AdjustedBalance,
    AdjustedBalanceMtd,
    AdjustedBalanceYtd,
    AdjustedTotalDisbursement,
    AdjustmentToBalances,
    AggregateBalanceAdjustments,
    Average1DayFloatMtd,
    Average1DayFloatYtd,
    Average2DayFloatMtd,
    Average2DayFloatYtd,
    AverageAdjustmentToBalancesMtd,
    AverageAdjustmentToBalancesYtd,
    AverageAvailablePreviousMonth,
    AverageClosingAvailableLastMonth,
    AverageClosingAvailableMtd,
    AverageClosingAvailableYtd,
    AverageClosingAvailableYtdLastMonth,
    AverageClosingLedgerMtd,
    AverageClosingLedgerPreviousMonth,
    AverageClosingLedgerYtd,
    AverageClosingLedgerYtdPreviousMonth,
    AverageCurrentAvailableMtd,
    AverageCurrentAvailableYtd,
    AverageOpeningAvailableMtd,
    AverageOpeningAvailableYtd,
    AverageOpeningLedgerMtd,
    AverageOpeningLedgerYtd,
    ClosingAvailable,
    ClosingLedger,
    CorporateTradePaymentCredits,
    CorporateTradePaymentDebits,
    CorporateTradePaymentSettlement,
    CorrespondentBankDeposit,
    CreditsNotDetailed,
    CurrentAvailable,
    CurrentAvailableCrsSupressed,
    CurrentDayTotalLockboxDeposits,
    CurrentLedger,
    CustomCreditSummary,
    CustomDebitSummary,
    CustomStatus,
    DebitsNotDetailed,
    DepositsSubjectToFloat,
    DisbursingFundingRequirement,
    DisbursingOpeningAvailableBalance,
    EdiTransactionCredit,
    EdiTransactionDebits,
    EstimatedTotalDisbursement,
    FiveDayFloat,
    FloatAdjustment,
    FourDayFloat,
    FrbFreightPaymentDebits,
    FrbPresentmentEstimate,
    GrandTotalCreditsLessGrandTotalDebits,
    InterceptDebits,
    InvestmentInterest,
    InvestmentSold,
    InvestmentsPurchased,
    LateDebitsAfterNotification,
    LateDeposit,
    ListPostCredits,
    ListPostDebits,
    LoanBalance,
    LoanDisbursement,
    MonthlyDividends,
    NetZeroBalanceAmount,
    OneDayFloat,
    OpeningAvailable,
    OpeningAvailableAndTotalSameDayAchDtcDeposit,
    OpeningLedger,
    SixDayFloat,
    TargetBalance,
    ThreeOrMoreDaysFloat,
    TodaysTotalDebits,
    TotalAchCredits,
    TotalAchDebits,
    TotalAchDisbursementFundingDebits,
    TotalAchDisbursingFundingCredits,
    TotalAchReturnItems,
    TotalAdjustmentCreditsYtd,
    TotalAmountOfSecuritiesPurchased,
    TotalAprDebits,
    TotalAtmCredits,
    TotalAtmDebits,
    TotalAutomaticTransferCredits,
    TotalAutomaticTransferDebits,
    TotalBackValueCredits,
    TotalBackValueDebits,
    TotalBankCardDeposits,
    TotalBankersAcceptanceCredits,
    TotalBankersAcceptancesDebit,
    TotalBankOriginatedDebits,
    TotalBankPreparedDeposits,
    TotalBookTransferCredits,
    TotalBookTransferDebits,
    TotalBrokerDebits,
    TotalBrokerDebitsChf,
    TotalBrokerDebitsFf,
    TotalBrokerDeposits,
    TotalBrokerDepositsChf,
    TotalBrokerDepositsFf,
    TotalCashCenterCredits,
    TotalCashCenterDebits,
    TotalCashLetterAdjustments,
    TotalCashLetterCredits,
    TotalCashLetterDebits,
    TotalCheckPaid,
    TotalCheckPaidCumulativeMtd,
    TotalChecksPostedAndReturned,
    TotalCollectionCredits,
    TotalCollectionDebit,
    TotalCommercialDeposits,
    TotalConcentrationCredits,
    TotalControlledDisbursingCredits,
    TotalControlledDisbursingDebits,
    TotalCreditAdjustment,
    TotalCreditAmountMtd,
    TotalCreditReversals,
    TotalCredits,
    TotalCreditsLessWireTransferAndReturnedChecks,
    TotalDebitAdjustments,
    TotalDebitAmountMtd,
    TotalDebitLessWireTransfersAndChargeBacks,
    TotalDebitReversals,
    TotalDebits,
    TotalDebitsExcludingReturnedItems,
    TotalDepositedItemsReturned,
    TotalDisbursingChecksPaidEarlyAmount,
    TotalDisbursingChecksPaidLastAmount,
    TotalDisbursingChecksPaidLaterAmount,
    TotalDtcCredits,
    TotalDtcDebits,
    TotalDtcDisbursingCredits,
    TotalEscrowCredits,
    TotalEscrowDebits,
    TotalFederalReserveBankCommercialBankDebit,
    TotalFedFundsPurchased,
    TotalFedFundsSold,
    TotalFloat,
    TotalForeignCheckPurchased,
    TotalFreightPaymentCredits,
    TotalFundsRequired,
    TotalIncomingMoneyTransfers,
    TotalInternationalCredits,
    TotalInternationalCreditsChf,
    TotalInternationalCreditsFf,
    TotalInternationalDebitChf,
    TotalInternationalDebitFf,
    TotalInternationalDebits,
    TotalInternationalMoneyTransferCredits,
    TotalInternationalMoneyTransferDebits,
    TotalInvestmentInterestDebits,
    TotalInvestmentPosition,
    TotalLettersOfCredit,
    TotalLoanPayment,
    TotalLoanPayments,
    TotalLoanProceeds,
    TotalLockboxDebits,
    TotalLockboxDeposits,
    TotalMiscellaneousCredits,
    TotalMiscellaneousDebits,
    TotalMiscellaneousDeposits,
    TotalMiscellaneousSecuritiesCreditsChf,
    TotalMiscellaneousSecuritiesCreditsFf,
    TotalMiscellaneousSecuritiesDbFf,
    TotalMiscellaneousSecuritiesDebitChf,
    TotalOtherCheckDeposits,
    TotalOutgoingMoneyTransfers,
    TotalPayableThroughDrafts,
    TotalPreauthorizedPaymentCredits,
    TotalRejectedCredits,
    TotalRejectedDebits,
    TotalSecuritiesInterest,
    TotalSecuritiesInterestChf,
    TotalSecuritiesInterestFf,
    TotalSecuritiesMatured,
    TotalSecuritiesMaturedChf,
    TotalSecuritiesMaturedFf,
    TotalSecuritiesPurchasedChf,
    TotalSecuritiesPurchasedFf,
    TotalSecuritiesSold,
    TotalSecuritiesSoldChf,
    TotalSecuritiesSoldFf,
    TotalSecurityCredits,
    TotalSecurityDebits,
    TotalTrustCredits,
    TotalTrustDebits,
    TotalUniversalCredits,
    TotalUniversalDebits,
    TotalValueDatedFunds,
    TotalWireTransfersInCHF,
    TotalWireTransfersInFF,
    TotalWireTransfersOutChf,
    TotalWireTransfersOutFf,
    TotalYtdAdjustment,
    TotalZbaCredits,
    TotalZbaDebits,
    TransferCalculation,
    TransferCalculationDebit,
    TwoOrMoreDaysFloat,
    Unknown,
    ZeroDayFloat,
}

impl AmountType {
    fn parse(type_code: &str) -> AmountType {
        match type_code {
            "010" => AmountType::OpeningLedger,
            "011" => AmountType::AverageOpeningLedgerMtd,
            "012" => AmountType::AverageOpeningLedgerYtd,
            "015" => AmountType::ClosingLedger,
            "020" => AmountType::AverageClosingLedgerMtd,
            "021" => AmountType::AverageClosingLedgerPreviousMonth,
            "022" => AmountType::AggregateBalanceAdjustments,
            "024" => AmountType::AverageClosingLedgerYtdPreviousMonth,
            "025" => AmountType::AverageClosingLedgerYtd,
            "030" => AmountType::CurrentLedger,
            "037" => AmountType::AchNetPosition,
            "039" => AmountType::OpeningAvailableAndTotalSameDayAchDtcDeposit,
            "040" => AmountType::OpeningAvailable,
            "041" => AmountType::AverageOpeningAvailableMtd,
            "042" => AmountType::AverageOpeningAvailableYtd,
            "043" => AmountType::AverageAvailablePreviousMonth,
            "044" => AmountType::DisbursingOpeningAvailableBalance,
            "045" => AmountType::ClosingAvailable,
            "050" => AmountType::AverageClosingAvailableMtd,
            "051" => AmountType::AverageClosingAvailableLastMonth,
            "054" => AmountType::AverageClosingAvailableYtdLastMonth,
            "055" => AmountType::AverageClosingAvailableYtd,
            "056" => AmountType::LoanBalance,
            "057" => AmountType::TotalInvestmentPosition,
            "059" => AmountType::CurrentAvailableCrsSupressed,
            "060" => AmountType::CurrentAvailable,
            "061" => AmountType::AverageCurrentAvailableMtd,
            "062" => AmountType::AverageCurrentAvailableYtd,
            "063" => AmountType::TotalFloat,
            "065" => AmountType::TargetBalance,
            "066" => AmountType::AdjustedBalance,
            "067" => AmountType::AdjustedBalanceMtd,
            "068" => AmountType::AdjustedBalanceYtd,
            "070" => AmountType::ZeroDayFloat,
            "072" => AmountType::OneDayFloat,
            "073" => AmountType::FloatAdjustment,
            "074" => AmountType::TwoOrMoreDaysFloat,
            "075" => AmountType::ThreeOrMoreDaysFloat,
            "076" => AmountType::AdjustmentToBalances,
            "077" => AmountType::AverageAdjustmentToBalancesMtd,
            "078" => AmountType::AverageAdjustmentToBalancesYtd,
            "079" => AmountType::FourDayFloat,
            "080" => AmountType::FiveDayFloat,
            "081" => AmountType::SixDayFloat,
            "082" => AmountType::Average1DayFloatMtd,
            "083" => AmountType::Average1DayFloatYtd,
            "084" => AmountType::Average2DayFloatMtd,
            "085" => AmountType::Average2DayFloatYtd,
            "086" => AmountType::TransferCalculation,
            "100" => AmountType::TotalCredits,
            "101" => AmountType::TotalCreditAmountMtd,
            "105" => AmountType::CreditsNotDetailed,
            "106" => AmountType::DepositsSubjectToFloat,
            "107" => AmountType::TotalAdjustmentCreditsYtd,
            "109" => AmountType::CurrentDayTotalLockboxDeposits,
            "110" => AmountType::TotalLockboxDeposits,
            "120" => AmountType::EdiTransactionCredit,
            "130" => AmountType::TotalConcentrationCredits,
            "131" => AmountType::TotalDtcCredits,
            "140" => AmountType::TotalAchCredits,
            "146" => AmountType::TotalBankCardDeposits,
            "150" => AmountType::TotalPreauthorizedPaymentCredits,
            "160" => AmountType::TotalAchDisbursingFundingCredits,
            "162" => AmountType::CorporateTradePaymentSettlement,
            "163" => AmountType::CorporateTradePaymentCredits,
            "167" => AmountType::AchSettlementCredits,
            "170" => AmountType::TotalOtherCheckDeposits,
            "178" => AmountType::ListPostCredits,
            "180" => AmountType::TotalLoanProceeds,
            "182" => AmountType::TotalBankPreparedDeposits,
            "185" => AmountType::TotalMiscellaneousDeposits,
            "186" => AmountType::TotalCashLetterCredits,
            "188" => AmountType::TotalCashLetterAdjustments,
            "190" => AmountType::TotalIncomingMoneyTransfers,
            "200" => AmountType::TotalAutomaticTransferCredits,
            "205" => AmountType::TotalBookTransferCredits,
            "207" => AmountType::TotalInternationalMoneyTransferCredits,
            "210" => AmountType::TotalInternationalCredits,
            "215" => AmountType::TotalLettersOfCredit,
            "230" => AmountType::TotalSecurityCredits,
            "231" => AmountType::TotalCollectionCredits,
            "239" => AmountType::TotalBankersAcceptanceCredits,
            "245" => AmountType::MonthlyDividends,
            "250" => AmountType::TotalChecksPostedAndReturned,
            "251" => AmountType::TotalDebitReversals,
            "256" => AmountType::TotalAchReturnItems,
            "260" => AmountType::TotalRejectedCredits,
            "270" => AmountType::TotalZbaCredits,
            "271" => AmountType::NetZeroBalanceAmount,
            "280" => AmountType::TotalControlledDisbursingCredits,
            "285" => AmountType::TotalDtcDisbursingCredits,
            "294" => AmountType::TotalAtmCredits,
            "302" => AmountType::CorrespondentBankDeposit,
            "303" => AmountType::TotalWireTransfersInFF,
            "304" => AmountType::TotalWireTransfersInCHF,
            "305" => AmountType::TotalFedFundsSold,
            "307" => AmountType::TotalTrustCredits,
            "309" => AmountType::TotalValueDatedFunds,
            "310" => AmountType::TotalCommercialDeposits,
            "315" => AmountType::TotalInternationalCreditsFf,
            "316" => AmountType::TotalInternationalCreditsChf,
            "318" => AmountType::TotalForeignCheckPurchased,
            "319" => AmountType::LateDeposit,
            "320" => AmountType::TotalSecuritiesSoldFf,
            "321" => AmountType::TotalSecuritiesSoldChf,
            "324" => AmountType::TotalSecuritiesMaturedFf,
            "325" => AmountType::TotalSecuritiesMaturedChf,
            "326" => AmountType::TotalSecuritiesInterest,
            "327" => AmountType::TotalSecuritiesMatured,
            "328" => AmountType::TotalSecuritiesInterestFf,
            "329" => AmountType::TotalSecuritiesInterestChf,
            "330" => AmountType::TotalEscrowCredits,
            "332" => AmountType::TotalMiscellaneousSecuritiesCreditsFf,
            "336" => AmountType::TotalMiscellaneousSecuritiesCreditsChf,
            "338" => AmountType::TotalSecuritiesSold,
            "340" => AmountType::TotalBrokerDeposits,
            "341" => AmountType::TotalBrokerDepositsFf,
            "343" => AmountType::TotalBrokerDepositsChf,
            "350" => AmountType::InvestmentSold,
            "352" => AmountType::TotalCashCenterCredits,
            "355" => AmountType::InvestmentInterest,
            "356" => AmountType::TotalCreditAdjustment,
            "360" => AmountType::TotalCreditsLessWireTransferAndReturnedChecks,
            "361" => AmountType::GrandTotalCreditsLessGrandTotalDebits,
            "370" => AmountType::TotalBackValueCredits,
            "385" => AmountType::TotalUniversalCredits,
            "389" => AmountType::TotalFreightPaymentCredits,
            "390" => AmountType::TotalMiscellaneousCredits,
            "400" => AmountType::TotalDebits,
            "401" => AmountType::TotalDebitAmountMtd,
            "403" => AmountType::TodaysTotalDebits,
            "405" => AmountType::TotalDebitLessWireTransfersAndChargeBacks,
            "406" => AmountType::DebitsNotDetailed,
            "410" => AmountType::TotalYtdAdjustment,
            "412" => AmountType::TotalDebitsExcludingReturnedItems,
            "416" => AmountType::TotalLockboxDebits,
            "420" => AmountType::EdiTransactionDebits,
            "430" => AmountType::TotalPayableThroughDrafts,
            "446" => AmountType::TotalAchDisbursementFundingDebits,
            "450" => AmountType::TotalAchDebits,
            "463" => AmountType::CorporateTradePaymentDebits,
            "465" => AmountType::CorporateTradePaymentSettlement,
            "467" => AmountType::AchSettlementDebits,
            "470" => AmountType::TotalCheckPaid,
            "471" => AmountType::TotalCheckPaidCumulativeMtd,
            "478" => AmountType::ListPostDebits,
            "480" => AmountType::TotalLoanPayments,
            "482" => AmountType::TotalBankOriginatedDebits,
            "486" => AmountType::TotalCashLetterDebits,
            "490" => AmountType::TotalOutgoingMoneyTransfers,
            "500" => AmountType::TotalAutomaticTransferDebits,
            "505" => AmountType::TotalBookTransferDebits,
            "507" => AmountType::TotalInternationalMoneyTransferDebits,
            "510" => AmountType::TotalInternationalDebits,
            "515" => AmountType::TotalLettersOfCredit,
            "530" => AmountType::TotalSecurityDebits,
            "532" => AmountType::TotalAmountOfSecuritiesPurchased,
            "534" => AmountType::TotalMiscellaneousSecuritiesDbFf,
            "536" => AmountType::TotalMiscellaneousSecuritiesDebitChf,
            "537" => AmountType::TotalCollectionDebit,
            "539" => AmountType::TotalBankersAcceptancesDebit,
            "550" => AmountType::TotalDepositedItemsReturned,
            "551" => AmountType::TotalCreditReversals,
            "556" => AmountType::TotalAchReturnItems,
            "560" => AmountType::TotalRejectedDebits,
            "570" => AmountType::TotalZbaDebits,
            "580" => AmountType::TotalControlledDisbursingDebits,
            "583" => AmountType::TotalDisbursingChecksPaidEarlyAmount,
            "584" => AmountType::TotalDisbursingChecksPaidLaterAmount,
            "585" => AmountType::DisbursingFundingRequirement,
            "586" => AmountType::FrbPresentmentEstimate,
            "587" => AmountType::LateDebitsAfterNotification,
            "588" => AmountType::TotalDisbursingChecksPaidLastAmount,
            "590" => AmountType::TotalDtcDebits,
            "594" => AmountType::TotalAtmDebits,
            "596" => AmountType::TotalAprDebits,
            "601" => AmountType::EstimatedTotalDisbursement,
            "602" => AmountType::AdjustedTotalDisbursement,
            "610" => AmountType::TotalFundsRequired,
            "611" => AmountType::TotalWireTransfersOutChf,
            "612" => AmountType::TotalWireTransfersOutFf,
            "613" => AmountType::TotalInternationalDebitChf,
            "614" => AmountType::TotalInternationalDebitFf,
            "615" => AmountType::TotalFederalReserveBankCommercialBankDebit,
            "617" => AmountType::TotalSecuritiesPurchasedChf,
            "618" => AmountType::TotalSecuritiesPurchasedFf,
            "621" => AmountType::TotalBrokerDebitsChf,
            "623" => AmountType::TotalBrokerDebitsFf,
            "625" => AmountType::TotalBrokerDebits,
            "626" => AmountType::TotalFedFundsPurchased,
            "628" => AmountType::TotalCashCenterDebits,
            "630" => AmountType::TotalDebitAdjustments,
            "632" => AmountType::TotalTrustDebits,
            "640" => AmountType::TotalEscrowDebits,
            "646" => AmountType::TransferCalculationDebit,
            "650" => AmountType::InvestmentsPurchased,
            "655" => AmountType::TotalInvestmentInterestDebits,
            "665" => AmountType::InterceptDebits,
            "670" => AmountType::TotalBackValueDebits,
            "685" => AmountType::TotalUniversalDebits,
            "689" => AmountType::FrbFreightPaymentDebits,
            "690" => AmountType::TotalMiscellaneousDebits,
            "720" => AmountType::TotalLoanPayment,
            "760" => AmountType::LoanDisbursement,
            code => match code.parse::<i16>() {
                Ok(n) if n >= 900 && n <= 919 => AmountType::CustomStatus,
                Ok(n) if n >= 920 && n <= 959 => AmountType::CustomCreditSummary,
                Ok(n) if n >= 960 && n <= 999 => AmountType::CustomDebitSummary,
                _ => AmountType::Unknown,
            },
        }
    }
}
